コード作成
Nagamoto-Koutarou/rasetech-java-1 pull request #1
Opened 2022-07-29 14:47 UTC by Nagamoto-Koutarou

遅くなりましたが、第2回講座の課題です。
改善点等、遠慮なく教えていただきたいです。
よろしくお願いします。

2022-07-29 15:03 UTC, Nagamoto-Koutarou commented
![スクリーンショット (101)](https://user-images.githubusercontent.com/109859819/181788314-38b90a4e-edae-4e80-8f55-4dd56b207439.png)
![スクリーンショット (102)](https://user-images.githubusercontent.com/109859819/181788373-5a1d5b53-aeef-4354-bceb-b5ea351871b8.png)
実行結果です。

2022-08-04 14:24 UTC, YudaiNoda3576 requested changes
コメントしました〜

2022-08-04 14:24 UTC, YudaiNoda3576 commented on src/Main.java
> +package PACKAGE_NAME;public class Main {
Mainクラスが二つあるように見えるのですがこちら不要でしたら削除してください！

2022-08-04 14:24 UTC, YudaiNoda3576 commented on Person.java
> +            } catch (InputMismatchException e) {
999999とかマイナスの数値が入力された場合は問題ないでしょうか？？

2023-01-30 14:24 UTC, merged